server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///${basedir}
          basedir:  target/config
#  security:
#      user:
#        password: 's3cret'
#  encrypt:
#    keyStore:
#        location: classpath:/server.jks
#        password: letmein
#        alias: devKey
#        secret: s3cret
